# Generated by Django 4.1.5 on 2023-01-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_profile_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
