# Generated by Django 4.1.5 on 2023-01-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_remove_profile_username_alter_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(choices=[('EN', 'English'), ('MA', 'Math'), ('SC', 'Science'), ('HI', 'History')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(choices=[('EL', 'Elementary'), ('MI', 'Middle School'), ('HI', 'High School'), ('CO', 'College')], max_length=2, null=True),
        ),
    ]
