# Generated by Django 4.1.5 on 2023-01-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
