# Generated by Django 4.1.5 on 2023-01-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subject',
        ),
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.CharField(choices=[('RE', 'Reading'), ('WR', 'Writing'), ('LI', 'Literature'), ('AR', 'Arithmetic'), ('GE', 'Geometry'), ('AL', 'Algebra'), ('CA', 'Calculus'), ('PH', 'Physics'), ('BI', 'Biology'), ('CH', 'Chemistry'), ('AM', 'American History'), ('WO', 'World History')], max_length=2, null=True),
        ),
    ]
