# Generated by Django 4.1.5 on 2023-01-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0010_choices_remove_profile_subject_profile_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RE', 'Reading'), ('WR', 'Writing'), ('LI', 'Literature'), ('AR', 'Arithmetic'), ('GE', 'Geometry'), ('AL', 'Algebra'), ('CA', 'Calculus'), ('PH', 'Physics'), ('BI', 'Biology'), ('CH', 'Chemistry'), ('AM', 'American History'), ('WO', 'World History')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.ManyToManyField(to='signup.option'),
        ),
    ]
