# Generated by Django 4.1.5 on 2023-01-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0012_alter_profile_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
