# Generated by Django 4.1.5 on 2023-01-29 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0013_remove_profile_subjects_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subject',
            new_name='subjects',
        ),
    ]
