# Generated by Django 4.1.5 on 2023-01-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0016_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
