# Generated by Django 4.1.5 on 2023-01-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0017_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blacklist',
            field=models.TextField(blank=True),
        ),
    ]
