# Generated by Django 4.1.5 on 2023-01-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0020_alter_profile_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='matched_list',
            field=models.TextField(blank=True, default=''),
        ),
    ]
