# Generated by Django 4.1.5 on 2023-01-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0021_profile_matched_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
