# Generated by Django 4.1.5 on 2023-01-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0022_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='signup/uploads/'),
        ),
    ]
