# Generated by Django 4.1.5 on 2023-01-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0024_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subjects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
